export default Object.freeze({
  AppName: 'Kulube',
  Order: 'Order',
  Counter: 'Counter',
  Kitchen: 'Kitchen',
  Welcome_to_order_entry: 'Welcome to order entry',
  Enter_customers_table_number_to_get_started:
    "Enter customer's table number to get started!",
  Enter_table_number_here: 'Enter table number here',
  BeingPrepared: 'Being prepared',
  Ready: 'Ready',
  Served: 'Served',
  Subtotal: 'Subtotal',
  Taxes: 'Taxes',
  Total: 'Total',
  moneySign: '$',
  Table: 'Table',
  View_cart: 'View cart',
  Note: 'Note',
  Submit_Order: 'Submit Order',
  Order_Entry: 'Order Entry',
  Special_Instructions: 'Special Instructions',
  Add_Note_Msg: 'Add a note (extra sauce, no onions, etc.)',
  DELETE_ORDER: 'DELETE ORDER',
  COLLECT: 'COLLECT',
  Unpaid_Orders: 'UNPAID ORDERS',
  Paid_Orders: 'PAID ORDERS',
  Orders: 'Orders',
  Are_You_Sure_Msg: 'Are you sure you want to delete the order?',
  Delete_Order: 'Delete Order',
  Cancel: 'Cancel',
  Table_number_cannot_be_empty: 'Table number cannot be empty',
  icon_not_found: 'icon not found',
  Server: 'Server',
  Orders_to_be_prepared: 'Orders to be prepared',
  Orders_ready_to_be_served: 'Orders ready to be served',
  Login: 'Login',
  Lets_have_a_great_day: 'Lets have a great day!',
  Employee_ID: 'Employee ID',
  Employee_Password: 'Employee Password',
  incorrectLoginMsg: 'Incorrect ID or password. Please try again!',
  incorrectLoginEntryMsg:
    'Employee ID and Employee Password must be longer than 4 characters!',
  Type_new_password: 'Type new password...',
  CHANGE_PASSWORD: 'CHANGE PASSWORD',
  incorrectPwdMsg: 'Password must be more than 4 digits!',
  Logout: 'Logout',
  Management: 'Management',
  Manage: 'Manage',
  bannerFailMsg: 'Your request has failed, Please try again!',
  orderSuccessMsg: 'Order has been submitted successfully!',
});
